name: App install and start

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [main, master]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3 #checkout code from repository, so we code downloaded in runner.
      - uses: actions/setup-node@v3 #setup nodejs in our runner
      - run: npm install #install pm2 global
      - run: pm2 delete matching-bot
      - run: pm2 list #check pm2 list
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start index.js --name matching-bot
